Raidboss: add e12s ja translation
quisquous/cactbot pull request #2224
Opened 2020-12-15 14:53 UTC by MaikoTan

https://github.com/quisquous/cactbot/blob/40997fd7785e8a5166a80e7b44ef8ef9e9e44d91/ui/raidboss/data/05-shb/raid/e12s.txt#L129

This is "Dark Water III / Eruption", right? if I am not misunderstand?

2020-12-15 14:55 UTC, MaikoTan commented on ui/raidboss/data/05-shb/raid/e12s.js
> +    ja: '対角',
@r4ha Folks in CN use 対角線 to describe intercards movement when I ask them,
but I don't very clear if folks in JP also use this word?

2020-12-16 07:31 UTC, r4ha requested changes

2020-12-16 08:18 UTC, MaikoTan commented on ui/raidboss/data/05-shb/raid/e12s.js
> +    ja: '対角',
http://kanatan.info/archives/25637304.html
はなつというスキル
ガルーダのパターン
![image](https://livedoor.blogimg.jp/kanatan_xh2og/imgs/c/d/cd4c9bcd.png)

2020-12-16 08:25 UTC, r4ha commented on ui/raidboss/data/05-shb/raid/e12s.js
> +    ja: '対角',
ありがとうございます！
日本のプレイヤーは"斜め"と言っているようです

2020-12-16 08:27 UTC, r4ha requested changes

2020-12-16 08:27 UTC, r4ha commented on ui/raidboss/data/05-shb/raid/e12s.js
> +    ja: '両側',
'横へ' is better here.

2020-12-16 08:34 UTC, MaikoTan commented on ui/raidboss/data/05-shb/raid/e12s.js
> +    ja: '対角',
そうですか!
勉強になりました！
Thank you very much! I'll change it when I return home.

2020-12-16 14:49 UTC, MaikoTan commented
All done!
It is safe to merge.

2020-12-16 23:36 UTC, merged