Raidboss: add some ja/cn translation in DRS
quisquous/cactbot pull request #2729
Opened 2021-04-15 00:24 UTC by MaikoTan

I don't very understand other gimmicks, so I leave it untranslated.
@ShadyWhite Pls review this PR, too.

2021-04-15 01:42 UTC, quisquous commented
> I don't very understand other gimmicks, so I leave it untranslated.

I am happy to give you video timestamps or more explanation of any triggers if that would be helpful!

2021-04-15 12:14 UTC, ShadyWhite requested changes

2021-04-15 12:14 UTC, ShadyWhite commented on ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.js
> +          cn: '躲在栅栏之后',
```suggestion
          cn: '躲在栅栏后',
```

2021-04-15 12:14 UTC, ShadyWhite commented on ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.js
> +          cn: '远离花',
```suggestion
          cn: '远离紫花',
```

2021-04-16 04:27 UTC, ShadyWhite approved these changes

2021-04-16 04:56 UTC, merged