raidboss: ASS Squeaky Clean cast
quisquous/cactbot pull request #5034
Opened 2022-10-31 23:54 UTC by KiroKai

Had a few instances where the Silken Puff would cast Squeaky Clean instead of Silkie.

[18:09:51.371] StartsCasting 14:4001B920:Silkie:7752:Squeaky Clean:4001B920:Silkie:4.200:-335.01:-170.00:471.00:3.14 [18:09:51.371] StartsCasting 14:4001B92D:Silken Puff:7756:Squeaky Clean:4001B92D:Silken Puff:8.900:-331.00:-159.00:471.00:0.00 [18:09:51.371] StartsCasting 14:4001B92E:Silken Puff:7754:Squeaky Clean:4001B92E:Silken Puff:7.400:-347.00:-159.00:471.00:0.00 [18:09:51.371] StartsCasting 14:4001B92F:Silkie:7753:Squeaky Clean:4001B92F:Silkie:5.700:-341.51:-165.65:471.00:2.50

2022-10-31 23:58 UTC, wexxlee commented
I think 7755/7756 may not be the optimal ability IDs to use for squeaky clean.  I've been using 7751 for Squeaky Clean Right and 7752 for Squeaky Clean Left, and it works consistently (and always originates from the boss).  It seems like 777[3-6] are less reliable and can originate from the adds.

2022-11-01 00:01 UTC, KiroKai commented
I personally had 7751 and 7752 in my personal triggers and they never failed like 5 and 6, so it seems like as you said they would be more optimal to use.

2022-11-01 00:06 UTC, wexxlee requested changes

2022-11-01 00:06 UTC, wexxlee commented on ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
> +      netRegex: { id: '7755', source: ['Silkie', 'Silken Puff'], capture: false },
```suggestion
      netRegex: { id: '7751', source: 'Silkie', capture: false },
```

2022-11-01 00:06 UTC, wexxlee commented on ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
> +      netRegex: { id: '7756', source: ['Silkie', 'Silken Puff'], capture: false },
```suggestion
      netRegex: { id: '7752', source: 'Silkie', capture: false },
```

2022-11-01 01:09 UTC, merged

2022-11-01 01:10 UTC, quisquous commented
cc @xiashtra re: these ability ids for savage

2022-11-01 07:25 UTC, xiashtra commented
I also had 7751/7752 in my original test triggers for normal, but deferred to @Legends0 on the initial pull.  I used the boss-only IDs for savage so those should be ok.